name = 'Sakura Clone'
license = 'GPL 2.0'
licenselink = 'https://github.com/Fuann-Kinoko/hugo-theme-sakura-clone/LICENSE'
description = "An incomplete port of the Hexo theme 'Sakura', which was originally ported from the WordPress theme 'Sakura'"

# The home page of the theme, where the source can be found
homepage = 'https://github.com/Fuann-Kinoko/hugo-theme-sakura-clone'

# Taxonomy terms
tags = ['blog']

# If the theme has a single author
[author]
  name = 'Fuann-Kinoko'

# If porting an existing theme
[original]
  author = 'honjun'
  repo = 'https://github.com/honjun/hexo-theme-sakura?tab=readme-ov-file'
